[tox]
requires = tox>=4
           tox-uv
envlist = py311, py312, py313, py314, flake8

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 cosmic_conn tests

[testenv]
extras = cpu
commands = pytest
