import os
import shutil

from astropy.io import fits


source_dir = 'data/pod_sync/SEP_dilation5'
target_dir = 'data/pod_sync/SEP_TEST_SET'

dirs_to_check = ['masked_fits', 'aligned_fits', 'banzai_frms']
files_to_move = []

for root, dirs, files in os.walk(target_dir):
    if os.path.basename(root) in dirs_to_check:
        # avoid temp files generated by Mac's Finder
        files = [f for f in files if not f[0] == '.']

        for f in files:
            hdu = fits.open(os.path.join(root, f))

            if root.endswith('aligned_fits'):
                files_to_move.append(hdu[1].header['filename'])
                files_to_move.append(hdu[2].header['filename'])
                files_to_move.append(hdu[3].header['filename'])
                print(files_to_move[-3:])

            # if root.endswith('banzai_frms'):
            #     files_to_move.append(f[:31])
            #     print(files_to_move[-1])


print('files to move', len(files_to_move))

count = 0
for root, dirs, files in os.walk(source_dir):
    if os.path.basename(root) == 'rejected_files':
        continue

    if os.path.basename(root) in dirs_to_check:
        # avoid temp files generated by Mac's Finder
        files = [f for f in files if not f[0] == '.']

        for f in files:

            if any(f[:31] in x for x in files_to_move):
                src = os.path.join(root, f)
                tgt = os.path.join(target_dir, os.path.basename(root), f)

                try:
                    shutil.move(src, tgt)

                    print(f'{src} moved to')
                    print(tgt)
                    print()
                    count += 1

                except:
                    print(f'{src} already moved')
                    print()

    if os.path.basename(root).endswith('train_set_eval'):
        files = [f for f in files if not f[0] == '.']

        for f in files:
            if not f.endswith('.png'):
                continue

            ff = f.split('_')[2]

            if any(ff[:31] in x for x in files_to_move):
                src = os.path.join(root, f)
                tgt = os.path.join(target_dir, os.path.basename(root), f)

                try:
                    shutil.move(src, tgt)

                    print(f'{src} moved to')
                    print(tgt)
                    print()
                    count += 1

                except:
                    print(f'{src} already moved')
                    print()


print('files removed', count)