import os

dirs_to_check = ['banzai_frms', 'aligned_fits']

source_dir = 'data/pod_sync/SEP_dilation5/elp1m0_2019_99s_done'
target_dir = 'data/elp1m0a_2019'

files_to_keep = []
for root, dirs, files in os.walk(source_dir):
    # if os.path.basename(root) == 'rejected_files':
    #     continue

    if os.path.basename(root) in dirs_to_check or 'rejected' in root:
        # avoid temp files generated by Mac's Finder
        files = [f[:31] for f in files if not f[0] == '.']
        files_to_keep += files

print('files to keep', len(files_to_keep))

count = 0
for root, dirs, files in os.walk(target_dir):
    # if os.path.basename(root) == 'rejected_files':
    #     continue

    if os.path.basename(root) in dirs_to_check:
        # avoid temp files generated by Mac's Finder
        files = [f for f in files if not f[0] == '.']

        for f in files:
            if any(f[:31] in x for x in files_to_keep):
                os.remove(os.path.join(root, f))
                print(f'{f} removed')
                count += 1

print(count)
print('files removed', count)