import os
from astropy.io import fits

dirs_to_check = ['banzai_frms', 'aligned_fits', 'masked_fits']
min_exp_time = 130.
target_dir = 'data/pod_sync/SEP_TEST_SET'

EXTENSIONS = ['fits', 'fz']

def is_fits_file(filename):
    filename = filename.lower()
    return any(filename.endswith(extension) for extension in EXTENSIONS)


for root, dirs, files in os.walk(target_dir):
    # avoid temp files generated by Mac's Finder
    files = [f for f in files if not f[0] == '.']

    for f in files:

        check_month = ['03', '04']
        if f[18:20] not in check_month:
            continue

        if is_fits_file(f):
            path = os.path.join(root, f)
        else:
            continue

        with fits.open(path) as hdu:
            hdr = hdu['SCI'].header

            sequence_frmtotal = hdr['FRMTOTAL']
            exptime = hdr['EXPTIME']

        # if sequence_frmtotal < 3 or sequence_frmtotal > 10:
        #     os.remove(path)
        #     print(f'{f} removed')
        
        if exptime < min_exp_time:
            os.remove(path)
            print(f'exp {exptime}, {f} removed')
